name: Build and Deploy Static Site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage and generate Istanbul report
        run: |
          npm run test:coverage
          ./node_modules/.bin/istanbul report lcov

      - name: Analyze code coverage with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # Pass the coverage report to SonarCloud using the generic coverage command
          SONAR_SCANNER_OPTS: "-Dsonar.coverage.exclusions='**/node_modules/**' -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info"
